// Pure types + helpers for the categorized Goals system.
// Safe to import from client + server.

export type GoalCategory = "Family" | "Fundamentals" | "Finance" | "Fitness";
export type GoalTimeframe =
  | "daily"
  | "week"
  | "quarter"
  | "year"
  | "custom";
export type GoalStatus = "active" | "successful" | "failed" | "archived";
export type GoalShare = "none" | "dropshipping" | "gym";
export type PledgeRecipient = "charity" | "tiktok";
// How the pledge evaluation script decides pass/fail per day for a goal:
//   counter: sum entries in content/goals/counter-logs/ matching counterSlug
//   tasks:   all Google Tasks for that day in `completed` status
export type DailySource = "counter" | "tasks";

export type Goal = {
  slug: string;
  title: string;
  description: string;
  // Long-form context for the goal. Shown behind an (i) info icon on
  // the card — click/hover opens a popup with this text.
  subDescription: string;
  category: GoalCategory;
  timeframe: GoalTimeframe;
  // Optional rollup: goals with the same `group` value are surfaced
  // together on /goals/ as a single grouped KPI.
  group: string;
  target: number;
  current: number;
  unit: string;
  startDate: string;
  deadline: string;
  status: GoalStatus;
  pinned: boolean;
  shareTo: GoalShare;
  // Pledge fields — honor system. We don't actually charge cards;
  // these power the dashboard, history, and "you owe $X" reminders.
  pledgeAmount: number;
  pledgeRecipient: PledgeRecipient;
  // How the evaluation script decides pass/fail.
  dailySource: DailySource;
  // Which counter feeds this goal (when dailySource === "counter").
  counterSlug: string;
  // Optional metric link — when set, current = sum of metric entries
  // within [startDate, deadline]. Independent of pledge evaluation.
  metricSlug: string;
  lastUpdated: string;
};

export type Metric = {
  slug: string;
  name: string;
  unit: string;
  description: string;
};

export type MetricEntry = {
  slug: string;
  metricSlug: string;
  date: string; // YYYY-MM-DD
  value: number;
  note: string;
};

export type CounterLog = {
  slug: string;
  date: string; // YYYY-MM-DD
  counter: string;
  value: number;
  note: string;
};

export type PledgeProof = {
  slug: string;
  date: string; // YYYY-MM-DD the goal failed
  goalSlug: string;
  tiktokUsername: string;
  tiktokAvatar: string;
  tiktokProfileUrl: string;
  screenshot: string;
  note: string;
};

// One evaluation record per goal per day. Generated by
// scripts/evaluate-pledges.mjs and cached as JSON; not persisted as
// markdown so retroactive counter-log changes update history naturally.
export type PledgeEvaluation = {
  goalSlug: string;
  goalTitle: string;
  category: GoalCategory;
  shareTo: GoalShare;
  date: string; // YYYY-MM-DD
  result: "successful" | "failed" | "pending";
  achieved: number;
  target: number;
  pledgeAmount: number;
  pledgeRecipient: PledgeRecipient;
};

export const CATEGORIES: GoalCategory[] = [
  "Family",
  "Fundamentals",
  "Finance",
  "Fitness",
];

export const TIMEFRAMES: Array<{ value: GoalTimeframe; label: string }> = [
  { value: "daily", label: "Daily" },
  { value: "week", label: "Week" },
  { value: "quarter", label: "Quarter" },
  { value: "year", label: "Year" },
  { value: "custom", label: "Custom" },
];

export const TIMEFRAME_ORDER: Record<GoalTimeframe, number> = {
  daily: 0,
  week: 1,
  quarter: 2,
  year: 3,
  custom: 4,
};

// % progress, clamped 0..100. Treats zero/negative targets as not yet
// computable (returns 0).
export function progressPct(goal: Goal): number {
  if (!goal.target || goal.target <= 0) return 0;
  const pct = (goal.current / goal.target) * 100;
  if (!Number.isFinite(pct)) return 0;
  return Math.max(0, Math.min(100, Math.round(pct)));
}

export function isActive(goal: Goal): boolean {
  return goal.status === "active";
}

export function daysUntil(iso: string): number {
  if (!iso) return 0;
  const target = new Date(iso).getTime();
  const now = Date.now();
  return Math.ceil((target - now) / (1000 * 60 * 60 * 24));
}

// Group active goals: same category + same timeframe + same `group` value
// become one rolled-up KPI on the /goals/ page. Goals without a `group`
// are returned as singleton groups (one goal per group).
export type GoalGroup = {
  key: string;
  category: GoalCategory;
  timeframe: GoalTimeframe;
  combinedPct: number;
  goals: Goal[];
};

export function groupGoals(goals: Goal[]): GoalGroup[] {
  const buckets = new Map<string, GoalGroup>();
  for (const g of goals) {
    const key = g.group
      ? `${g.category}|${g.timeframe}|${g.group}`
      : `${g.category}|${g.timeframe}|${g.slug}`;
    let bucket = buckets.get(key);
    if (!bucket) {
      bucket = {
        key,
        category: g.category,
        timeframe: g.timeframe,
        combinedPct: 0,
        goals: [],
      };
      buckets.set(key, bucket);
    }
    bucket.goals.push(g);
  }
  for (const b of buckets.values()) {
    if (b.goals.length === 0) continue;
    const sum = b.goals.reduce((s, g) => s + progressPct(g), 0);
    b.combinedPct = Math.round(sum / b.goals.length);
  }
  return Array.from(buckets.values()).sort((a, b) => {
    if (a.category !== b.category) {
      return CATEGORIES.indexOf(a.category) - CATEGORIES.indexOf(b.category);
    }
    return TIMEFRAME_ORDER[a.timeframe] - TIMEFRAME_ORDER[b.timeframe];
  });
}

// A pledge goal is any active goal with a non-zero pledge amount.
export function isPledgeGoal(goal: Goal): boolean {
  return goal.pledgeAmount > 0 && goal.status === "active";
}
